### ISSUE TITLE
faiss 1.7.4 install error

### ISSUE THREAD

**Issue by matsui528** [matsui528/faiss_build_monitor#1]
This issue reports the error log for installing faiss 1.7.4.

The main package of faiss 1.7.4 seems to have some problems with loading mkl libraries, e.g.,

```console
Python 3.10.11
Traceback (most recent call last):
  File "/home/runner/work/faiss_build_monitor/faiss_build_monitor/run.py", line 1, in <module>
    import faiss
  File "/usr/share/miniconda3/envs/test/lib/python3.10/site-packages/faiss/__init__.py", line 16, in <module>
    from .loader import *
  File "/usr/share/miniconda3/envs/test/lib/python3.10/site-packages/faiss/loader.py", line 65, in <module>
    from .swigfaiss import *
  File "/usr/share/miniconda3/envs/test/lib/python3.10/site-packages/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory
Error: Process completed with exit code 1.
```

As of May 26, 2023, the following configurations work, but other configuration such as `ubuntu, py3.10, main, faiss 1.7.4` does not work.
- Ubuntu, python 3.9, main package, faiss 1.7.3
- Ubuntu, python 3.9, nightly package, faiss 1.7.4
- Ubuntu, python 3.10, nightly package, faiss 1.7.4
- Mac OS, python 3.9, main package, faiss 1.7.3
- Windows, python 3.9, nightly package, faiss 1.7.4
- Windows, python 3.10, nightly package, faiss 1.7.4

Note that I tested the following combinations:
- os: {ubuntu-latest, macos-latest, windows-latest}
- python-version: {3.9, 3.10}
- faiss-label: {main, nightly}
- faiss-version: {1.7.3, 1.7.4}

See [here](https://github.com/matsui528/faiss_build_monitor/blob/main/.github/workflows/build_faiss.yml) for the workflow and [here](https://github.com/matsui528/faiss_build_monitor/actions/workflows/build_faiss.yml) for the build log.

**Comment by matsui528** [comment]
Related: https://github.com/matsui528/nanopq/pull/28, https://github.com/kyamagu/faiss-wheels/issues/75, https://github.com/facebookresearch/faiss/issues/2859, https://github.com/facebookresearch/faiss/issues/2852, https://github.com/facebookresearch/faiss/pull/2856 https://github.com/facebookresearch/faiss/issues/2883 https://github.com/facebookresearch/faiss/pull/2880 https://github.com/facebookresearch/faiss/issues/2890

**Comment by matsui528** [comment]
Updated on June 28.


# Work:
- Ubuntu, python 3.9, main package, faiss 1.7.3
- Ubuntu, python 3.9, nightly package, faiss 1.7.4
- Ubuntu, python 3.10, nightly package, faiss 1.7.4
- Mac OS, python 3.9, main package, faiss 1.7.3
- Mac OS, python 3.9, nightly package, faiss 1.7.4
- Mac OS, python 3.10, nightly package, faiss 1.7.4
- Windows, python 3.9, nightly package, faiss 1.7.4
- Windows, python 3.10, nightly package, faiss 1.7.4

# Not work:
- Ubuntu, python 3.9, main package, faiss 1.7.4
- Ubuntu, python 3.9, nightly package, faiss 1.7.3
- Ubuntu, python 3.10, main package, faiss 1.7.4
- Ubuntu, python 3.10, nightly package, faiss 1.7.3
- Mac OS, python 3.9, main package, faiss 1.7.4
- Mac OS, python 3.9, nightly package, faiss 1.7.3
- Mac OS, python 3.10, main package, faiss 1.7.4
- Mac OS, python 3.10, nightly package, faiss 1.7.3
- Windows, python 3.9, main package, faiss 1.7.4
- Windows, python 3.9, nightly package, faiss 1.7.3
- Windows, python 3.10, main package, faiss 1.7.4
- Windows, python 3.10, nightly package, faiss 1.7.3
